---
title: "L01 Review"
subtitle: "Data Science 3 with R (STAT 301-3)"
author: "Ellie Carney"
pagetitle: "L01 Ellie Carney"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin   
---

::: {.callout-tip icon="false"}
## Github Repo Link

[Github Repo Link](https://github.com/stat301-3-2026-spring/l01-review-elliecarney.git)

:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution

- split data into training and testing sets, with more data reserved for training. 
- if conducting a resampling process, fold the training data into a set for resampling.
- conduct an EDA and create a recipe with any necessary preprocessing steps performed on the data.
- set the engine for the model(s). if conducting a resampling process, set parameters that need to be tuned.
- if conducting a resampling process, define the grid that the parameters will be tuned on.
- create a workflow.
- fit the workflow to the training data/resampling data. 
- if conducting resampling process, compare the model performance and select the best performing model and fit it to the entire training data.
- evaluate model performance by testing how well it predicts the outcome variable on the testing data.

:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution

Supervised learning involves a target variable and observes patterns between the relationship between a set of predictors and the target variable. Unsupervised learning observes patterns in the data without a select target variable.

:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

A descriptive model summarizes or visually depicts an existing characteristic or trend in the data.

:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

An inferential model aims to answer a research question based on underlying relationships in the data.

:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

A predictive model aims to create the most accurate prediction possible for future or a new set of data.

:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution



:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE

:::

